name: Free Windows VPS

on:
  workflow_dispatch:

jobs:
  free-vps:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Show VPS info
        run: |
          echo "Your temporary VPS is ready!"
          systeminfo
          whoami
