name: Windows-RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Start Message
      run: echo "Starting Windows RDP setup..."

    - name: Enable RDP Service
      run: |
        Set-Service -Name TermService -StartupType Automatic
        Start-Service -Name TermService
        Write-Host "RDP Service Started Successfully"

    - name: Install Chocolatey
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Ngrok
      shell: powershell
      run: choco install ngrok -y

    - name: Authenticate Ngrok
      shell: powershell
      run: ngrok authtoken 3Ak8VSOurS40ZJ09YqCHxqy70Xh_Q1B9GbHveGZTeuyrzhkq

    - name: Start RDP Tunnel
      shell: powershell
      run: |
        Start-Process ngrok -ArgumentList "tcp 3389" -NoNewWindow
        Start-Sleep -Seconds 15
        Invoke-RestMethod http://127.0.0.1:4040/api/tunnels

    - name: Keep Session Alive
      shell: powershell
      run: |
        Write-Host "RDP session will stay active for 6 hours"
        Start-Sleep -Seconds 21600
